title: Aman's blog
author: Aman Pratap Singh
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog for Github Lab exercise.
# social links
twitter_username: ultimateaps
github_username:  apsknight

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
